version: '3'
services:

  prefect_etl:
    build: ./prefect
    tty: true
    ports:
      - 4200:4200
    hostname: prefect

  postgres_database:
    build: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always
    hostname: postgres

